apiVersion: v2
appVersion: 2.12.0
dependencies:
- condition: monitoring.enabled
  name: monitoring
  repository: "file://./charts/monitoring"
  version: 2.7.0
- condition: ui.enabled
  name: ui
  repository: "file://./charts/ui"
  version: 2.8.0
- condition: kyvernoPlugin.enabled
  name: kyvernoPlugin
  repository: "file://./charts/kyvernoPlugin"
  version: 1.5.1
description: 'Policy Reporter watches for PolicyReport Resources. It creates Prometheus
  Metrics and can send rule validation events to different targets like Loki, Elasticsearch,
  Slack or Discord '
home: https://kyverno.github.io/policy-reporter
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
maintainers:
- name: Frank Jogeleit
name: policy-reporter
sources:
- https://github.com/kyverno/policy-reporter
type: application
version: 2.16.0
