resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

ui:
  enabled: true

ingres:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce

kyvernoPlugin:
  enabled: true
