resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

ui:
  enabled: true
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: kyverno.development.ctd.tools
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 8080

target:
  ui:
    host: kyverno.development.ctd.tools

kyvernoPlugin:
  enabled: true
