resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

ui:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
    hosts:
      - host: kyverno-test.development.ctd.tools
        paths:
          - path: /
            pathType: Prefix

kyvernoPlugin:
  enabled: true
