apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
    name: karma-oauth-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }} 
  target:
    name: karma-oauth-secrets
    creationPolicy: Owner
  data: 
  - secretKey: client-id
    remoteRef:
      key: GRAFANA_OAUTH_CLIENT_ID  
  - secretKey: client-secret
    remoteRef:
      key: GRAFANA_OAUTH_CLIENT_SECRET 
  - secretKey: cookie-secret
    remoteRef:
      key:  OAUTH2_PROXY_COOKIE_SECRET  
