apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
    name: kyverno-oauth-secrets
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    name: kyverno-oauth-secrets
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: KYVERNO_OAUTH_CLIENT_ID
  - secretKey: client-secret
    remoteRef:
      key: KYVERNO_OAUTH_CLIENT_SECRET
  - secretKey: cookie-secret
    remoteRef:
      key:  OAUTH2_PROXY_COOKIE_SECRET
